{{- if not .Values.rbac.only }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telepresence.fullname" . }}
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "telepresence.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "telepresence.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          - name: SYSTEMA_HOST
            value: app.getambassador.io
          - name: SYSTEMA_PORT
            value: "443"
          - name: TELEPRESENCE_REGISTRY
            value: {{ .Values.image.registry }}
          - name: MANAGER_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          ports:
          - name: api
            containerPort: 8081
          - name: https
            containerPort: 8443
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.licenseKey.create }}
          - name: license
            mountPath: /home/telepresence
            readOnly: true
          {{- end }}
          {{- if .Values.agentInjector.create }}
          - name: tls
            mountPath: /var/run/secrets/tls
            readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.licenseKey.create }}
      - name: license
        secret: 
          defaultMode: 420
          secretName: {{ .Values.licenseKey.secret.name }}
      {{- end }}
      {{- if .Values.agentInjector.create }}
      - name: tls
        secret:
          defaultMode: 420
          secretName: {{ .Values.agentInjector.secret.name }}
      {{- end }}
      serviceAccount: traffic-manager
      serviceAccountName: traffic-manager
{{- end }}
